### ISSUE TITLE
Upper/lowercase inconsistency 

### ISSUE THREAD

**Issue by MadCatX** [Molecular-Biophysics-Database/mbdb-model#69]
At least in `oarepo` representations there appears to be an inconsistency in letter case. At least `general parameters` section is referred to as `General_parameters` (capital G) in `general_parameters.yaml` but as `general_parameters` (lowercase g) in other models that inline it. A case-sensitive interpreter then sees these as two different models. This is causing issues in [mbdb-input-ui](https://github.com/Molecular-Biophysics-Database/mbdb-input-ui/) which now reads General Parameters from `general_parameters.yaml` instead of the inlined definitions.

**Comment by edager** [comment]
technically this is not an inconsistency as that file was never intended as everything else as an include. In the  models it's corrct
